# .github/workflows/douban.yml
name: douban
on: 
  schedule:
      - cron: "18 35 6 * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 164528743
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 164528743
        type: book
        format: csv
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban'
